## *1. What does Pandas stand for?*
-Panel Data", and "Python Data
## *2. What are the 2 collections used in Pandas?*
series and dataframes
## *3. Name 4 things Pandas can do for us.*
    - 1. load
    - 2. manipulate
    - 3. prepare
    - 4. model
    - 5. analyze

## *4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?*
-inplace=True

## *5. What is a CSV?*
-Comma speparated by value creating a datasheet for tabular information

## *6. When cleaning data what values do we not like in our data?*
-Nulls, NaN

In [58]:
# Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`
import numpy as np

arr = np.array(["A", "B", "C", "D", "a", "b", "c", "d", "e", "Andrew", "J", "Hardaway"])
rArr = arr.reshape(2,3,2)
print(rArr)

# 8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20
val = np.linspace(0, 20, 6)
print(val)

# 9. Make a Deep Copy of the above array
valDC = np.copy(val)
print(valDC)


# 10. Concatenate these 3 arrays into a new array named 'newArray'...
#     ```python
#             ([[25, 16]])
#             ([[11, 2], [13, 4]])
#             ([[7, 81], [5, 6], [11, 12]])
#     ```
arr2 = np.array([[25, 16]])
arr3 = np.array([[11, 2], [13, 4]])
arr4 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arr2, arr3, arr4), axis=0)
print("newArray==", newArray)


# 11. Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)

print(sortedArray)

# 12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.

(a,b) = rArr

print("Unpacked array tuples=", a,b)

# 13. Combined and sort the following arrays into one called 'comboArray' ...

#     ```python
#         one = ([10, 11, 12, 13, 14, 15, 16, 17])
#         two = ([20, 21, 22, 23, 24, 25, 26, 27])
#         three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
#     ```

array1 = np.array([10, 11, 12, 13, 14, 15, 16, 17])
array2 = np.array([20, 21, 22, 23, 24, 25, 26, 27])
array3 = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboA= np.concatenate((array1, array2, array3), axis=0)
comboArray= np.sort(comboA)
print("comboArray =", comboArray)

# 14. Take 'comboArray' and perform the following slicing activities:
#     - print sec1 - the 2nd element
#     - print sec2 - all elements from the 3rd element to the last
#     - print sec3 - all elements from the 4th to the 14th elements
#     - print sec4 - the last 6 elements
#     - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
#     - print sec6 - from #20 every even element to the end
#     - print sec7 - from the last element moving forward, every 5th element.
sec1 = comboArray[1]
print(sec1)
sec2 = comboArray[2:]
print(sec2)
sec3 = comboArray[3:14]
print(sec3)
sec4= comboArray[:-6]
print(sec4)
sec5 = comboArray[:-10]
print(sec5)
sec6 = comboArray[16::2]
print(sec6)
sec7 = comboArray[::-5]
print(sec7)

[[['A' 'B']
  ['C' 'D']
  ['a' 'b']]

 [['c' 'd']
  ['e' 'Andrew']
  ['J' 'Hardaway']]]
[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]
newArray== [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]
[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]
Unpacked array tuples= [['A' 'B']
 ['C' 'D']
 ['a' 'b']] [['c' 'd']
 ['e' 'Andrew']
 ['J' 'Hardaway']]
comboArray = [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]

In [102]:
# 15. Using `Series`, create a `DataFrame` that looks like this:

#     | Ingredients | Quantity | Unit |
#     |----|----|----|
#     | Flour | 4 | cups |
#     | Milk | 1 | cup |
#     | Eggs | 2 | large |
#     | Spam | 1 | can |

#     Name: Dinner, dtype: object

import pandas as pd

Ingredients=pd.Series(["Flour", "Milk", "Eggs", "Spam"])
Quanitity = pd.Series(['4', '1', '2', '1'])
Unit = pd.Series(["cups", "cups", "large", "can"])

df = pd.DataFrame({"Ingredients" : Ingredients, "Quantity" : Quanitity, "Unit":Unit})

df.name = "Components"
print (df)

# 16. Take this data and create a DataFrame named studentData
#     ```Python
#         {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#             'Height': [5.1, 6.2, 5.1, 5.2],
#             'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#             'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#             'Age': [21, 23, 24, 21],
#             'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#             'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
#         }
#     ```

Student_Data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
            'Height': [5.1, 6.2, 5.1, 5.2],
            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
            'Age': [21, 23, 24, 21],
            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

StudentData = pd.DataFrame(Student_Data)
print(StudentData)

import pandas as pd

# Name=pd.Series(["Jai", "janusha", "Gaurav", "Anuj"])
# Height = pd.Series([5.1, 6.2, 5.1, 5.2])
# address = pd.Series(['Msc', 'MA', 'Msc', 'Msc'])
# Age =  [21, 23, 24, 21],
# Pets = ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
# sport = ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']

# df = pd.DataFrame({"Name" : Name, "Height" : Height, "Age": Age, "address" : address, "pets": Pets, "sports":sport})

# df.name = "Student Data"
# print (df)

# 17. Add a new column to the DataFrame with the following deserts:
#         ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
StudentData['deserts'] = deserts

print(StudentData)

# df = pd.DataFrame(StudentData.append(deserts,
#                                     ignore_index = True)


# 18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
import pandas as pd
StudentData.sort_values(by =['Name','address'],ascending=[True,True], inplace = True)

print(StudentData)

# 19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

#     ```python
#         df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
#     ```

# df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
# df.to_cvs('cows_and_goats.csv')

# print("DataFrame and Save CSV")

import pandas as pd
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')



# 20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

import pandas as pd
Vegetable = pd.DataFrame([["Spinach", "Broccoli"], ["GreeenBeans", "Celery"]],
                        columns=["Morning", "Afternoon"])
Vegetable.to_csv('Vegetables.csv')

  Ingredients Quantity   Unit
0       Flour        4   cups
1        Milk        1   cups
2        Eggs        2  large
3        Spam        1    can
      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

        deserts
0     ice cream
1  Cashew Fudge
2       waffels
3  Carrot Halwa
      Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball

        deserts
3  Carrot Halwa
2       waffels
0     ice cream
1  Cashew Fudge